### ISSUE TITLE
Refactor soda-csi-provisioner code

### ISSUE THREAD

**Issue by asifdxtreme** [sodafoundation/nbp#383]
**Issue/Feature Description:**
The base code of Soda-csi-provisioner code has been taken from https://github.com/kubernetes-csi/external-provisioner and on the top of it the SODA API changes has been done, now this code contains all the vendor code as well which bring along 2800+ files.
**Why this issue to fixed / feature is needed(give scenarios or use cases):**
This issues brings in lot of code redundant code which might be difficult to maintain in future

We need to brainstorm and find the best way to manage ths code as other side cars also needs to be imported in csi-plug-n-play.

**Comment by kumarashit** [comment]
The CSI PnP code is merged. @asifdxtreme Please check and  close this
