### ISSUE TITLE
Deploy multiple csi drivers in single k8s deployment with soda-csi-provisioner

### ISSUE THREAD

**Issue by asifdxtreme** [sodafoundation/nbp#410]
**Issue/Feature Description:**
Currently multiple CSI drivers cannot be deployed in a single k8s deployment using soda-csi-provisioner as only one csi driver can hold the lock for `soda-csi`

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
This needs to be fixed to support heterogeneous support for soda-csi plug n play

**How to reproduce, in case of a bug:**
Deploy 2 CSI drivers with soda-csi-provisioner image

**Comment by Click2cloud-Ceres** [comment]
We have tried the above-mentioned issue with different CSI drivers and came to some conclusions which are listed below :

1. If there are more than one CSI driver from the same storage vendor, it should be deployed in a different namespace to avoid the soda-csi lock conflicts.
for example : 
we have used OPENEBS-LVM CSI driver in Kube-system namespace and OPENEBS-ZFS CSI driver in Kube-system-zfs namespace,
both were working without holding any locks for soda-csi.


2. CSI drivers from different storage vendors can be deployed in the same namespace without having any conflict.
for example :
we have used the CEPH-RBD CSI driver and  IBM CSI driver both in the default namespace and didn't notice any soda-csi lock conflict issue.

**Comment by asifdxtreme** [comment]
@Click2cloud-Ceres Thanks for digging into this issue, Can you please add this Note statement in the document over here https://docs.sodafoundation.io/guides/integration-guides/csi-integration/soda-csi-pnp/#prerequisite

**Comment by Click2cloud-Ceres** [comment]
sure sir I have committed the changes in the below-mentioned PR. I request you to review it and suggest if any changes required.
https://github.com/sodafoundation/documentation/pull/163
thanx.

**Comment by asifdxtreme** [comment]
Related Pr's have been merged in Documentation Repo, going ahead to close this issue
